### ISSUE TITLE
Problem with resolution (or maybe just me)

### ISSUE THREAD

**Issue by MildCurry** [PlGGS/ElDewrito-Multi-Instance#1]
So when I try and set the resolutions for the profiles I obviously want to make them non standard so they can take full advantage of the screen i have (is 4k television but i dont think that should matter)

the problem is that when i try to do so, what i think happens is that the windows default to the closest resolution out of the in game options rather than sticking with the non standard one i input.

or maybe its just me, I put both my profiles (2 players) in 2160 (H) by 1080 (V) with the global options all on except fullscreen. Hope this helps or hope you can help me fix what im doing wrong and I would like to thank you and the great work your doing here

**Comment by PlGGS** [comment]
Please make sure to add custom resolutions in Nvidia control panel before launching instances with that resolution. I'll see if I can programmatically add them before launching

**Comment by MildCurry** [comment]
thanks for the help however i still for the life of me cant figure this out, when i try to set a custom resolution i get the test but after my screen comes back on it just doesnt give me an option to create the resolution.

**Comment by PlGGS** [comment]
[are you doing this?](https://www.youtube.com/watch?v=o3SYetRiZcI)

**Comment by MildCurry** [comment]
yup, but when you can click the test button to try and use that resolution, the pc just cuts off signal to the monitor for probably 20-ish seconds and then when it comes back on there is no change or any option to do anything, as if i hadnt pressed anything at all.

this is a TV if that has anything to do with it but im not sure it does but I had read about TV's not working right with this but i don't see a reason as to why

**Comment by PlGGS** [comment]
Hmm maybe just press enter while the screen is blank to save the resolution anyway and try to use it for the game window and never for an actual monitor's display resolution
