### ISSUE TITLE
Cant get players 5-8 working (Or maybe just me)

### ISSUE THREAD

**Issue by TannerLevi** [PlGGS/ElDewrito-Multi-Instance#3]
First I must say thank you so much PIGGS for making this. We have played hours of 4 player with siblings and cousins on my op laptop connected to TVs. Could not have been more stoked to have found your program.
Thanks immensely. I have sent several people this Link. So we have 8  360 controllers with two Microsoft Xbox 360 Wireless Receivers (which support 4 360 controllers a piece. I can get all 8 controllers connected between the two Microsoft Xbox 360 Wireless Receivers no problem. But when opening 8 instances of Halo only the first 4 controllers work that are connected to the first wireless receiver.
I also have 2 wired 360 connector charger cables and this does not work either. Only the first 4 wireless controllers work and no more. Any ideas or help would be much appreciated.

**Comment by PlGGS** [comment]
Oh, hey thanks! Yeah, you need an xbox one controller adapter. The 360 adapter and driver only support up to 4 active controller connections at once. Although technically, you could get 5 players in by letting someone use keyboard and mouse!

Sorry about that. Glad to hear you're enjoying the program though!

**Comment by TannerLevi** [comment]
Gotcha! no worries. So only xbox one controllers would work for 8 players?
Do you think 4 xbox one controllers connected to the xbox one adapter + 4 360 controllers connected to the xbox 360 adapter would work? Or would only 8 xbox one controllers connected to the single xbox one adapter work? Thanks for the help!

**Comment by PlGGS** [comment]
Hey, yeah as soon as you have the 360 controller connector involved, the maximum amount of players would be 4, as that's the max that adapter can handle. If you were to connect 4 to the 360 adapter and 4 to the Xbone adapter they would more than likely all be handled by the first four xinput spots, so spots 5-8 would never be filled.

Technically, if you had 8 Xbone controllers and connected them all in addition to 4 360 controllers, you may be able to use 4 360 and 4 Xbone, but at that point, it would make much more sense just to use all Xbone controllers lol

**Comment by TannerLevi** [comment]
Perfect! thanks bro. I ordered a lot of 8 OEM xbox one controllers and the adapter for 199 off ebay. I am just going to sell these 360 controllers now. It was a perfect excuse to upgrade from these old controllers.  Thanks again

**Comment by PlGGS** [comment]
Damn that's a steal! Np man

**Comment by TannerLevi** [comment]
Hey Piggs, hope your having a great summer.
 So I have all 8 Xbox one controllers controllers connected via one
Microsoft 8 controller USB adapter. However only the first 4 instances work
with controllers 1-4. Any ideas or help I would appreciate greatly! Thx in
advanced
